name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGmD-thzn1LVVmDb7w.kehwIZmIQ94"
            index: 0
          - recaptcha_token: "thr1.AAAAAGmD-4Nm-wgcI5Pw1Q.ygmC29ADtsQ"
            index: 1
          - recaptcha_token: "thr1.AAAAAGmD-5YJpXwzsD1P9w.uwn82DluMaY"
            index: 2
          - recaptcha_token: "thr1.AAAAAGmD-9j5gawYxc6-Rg.zxmoLdK2InM"
            index: 3
          - recaptcha_token: "thr1.AAAAAGmD_B4j2VwySjyCDg.iwTL83U0O8o"
            index: 4
          - recaptcha_token: "thr1.AAAAAGmD_JCVoQSV_0kEvw.hT_yEasozwA"
            index: 5
          - recaptcha_token: "thr1.AAAAAGmD_PR89oVmR-WpLg.I_GQk5Pu6wI"
            index: 6
          - recaptcha_token: "thr1.AAAAAGmD_TK1gtREYaq_Tw.Ntqxk96L_Qw"
            index: 7
          - recaptcha_token: "thr1.AAAAAGmD_U2eUxKyqnnI8g.SQ0nnUklv10"
            index: 8
          - recaptcha_token: "thr1.AAAAAGmD_XGLcH4M22pUcA.v1xtizkjhl4"
            index: 9
          - recaptcha_token: "thr1.AAAAAGmD_ZuC7xDurEEdfw.0ZdwtirI_xM"
            index: 10
          - recaptcha_token: "thr1.AAAAAGmD_eQGfgoOjgUuyA.1gzYbIm3bPE"
            index: 11
          - recaptcha_token: "thr1.AAAAAGmD_uwKAutnpOZRIw.O4zH8RAFPCg"
            index: 12
          - recaptcha_token: "thr1.AAAAAGmD_vrn64RfvQi0rA.x0zrdC6-cDU"
            index: 13
          - recaptcha_token: "thr1.AAAAAGmD_xrVEaatDDutSw.gnzlsZ3lh8s"
            index: 14
          - recaptcha_token: "thr1.AAAAAGmD_y1l8Jyyq9EDiA.BvnRkuVDTZY"

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
