name: Host - Recaptcha Rooms - Group 2

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts-group2
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGmQwADb9aqrmz4-rg.tqt7EWWlgkg"
            index: 0
          - recaptcha_token: "thr1.AAAAAGmQwCFG_K9FgANHxg.6C0bVhGdQ_Q"
            index: 1
          - recaptcha_token: "thr1.AAAAAGmQwCFndLYNYmBlnA.JMukJFeNJJY"
            index: 2
          - recaptcha_token: "thr1.AAAAAGmQwTsbcrHsOCulGQ._XPhDtwc_hs"
            index: 3
          - recaptcha_token: "thr1.AAAAAGmQwTsgJB4D71AYsQ.rAambWMzMcU"
            index: 4
          - recaptcha_token: "thr1.AAAAAGmQwYuD3v2_Q0VlAQ.F5kbop4KPWw"
            index: 5
          - recaptcha_token: "thr1.AAAAAGmQwbdS7Da87vSmnQ.LTPmNG1vkPQ"
            index: 6
          - recaptcha_token: "thr1.AAAAAGmQxECSm0Dh1H4JZg.b2G41ezs61I"
            index: 7
          - recaptcha_token: "thr1.AAAAAGmQxGSIWqDy0cpKSg.5s-F_xKNrnA"
            index: 8
          - recaptcha_token: "thr1.AAAAAGmQxH588J7GNa1M-w.HMUWozqJ1iY"
            index: 9
          - recaptcha_token: "thr1.AAAAAGmQxJ-8Wc2fNosadw.7ylwmpcamCk"
            index: 10
          - recaptcha_token: "thr1.AAAAAGmQxMcYzAhtaFTD5w.TJlZf_FcW18"
            index: 11
          - recaptcha_token: "thr1.AAAAAGmQxK6cnAQhaZgm8Q.dSXsFcxu_rI"
            index: 12
          - recaptcha_token: "thr1.AAAAAGmQxPJUQ6gV2aRCkQ._Hemt1guNME"
            index: 13

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
