name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_rooms:
        description: 'Links de las salas (separados por coma)'
        required: true
        default: 'https://www.haxball.com/play?c=1n05nbF698Q,https://www.haxball.com/play?c=2,https://www.haxball.com/play?c=3'
      mensaje:
        description: 'Mensaje principal de los bots'
        required: true
        default: 'Raid por Stefano365p'
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'admin'
      password:
        description: 'Contrase√±a de la sala (opcional)'
        required: false
        default: ''

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        include:
          - { job_index: 0, job_id: Basro1 }
          - { job_index: 1, job_id: Basro2 }
          - { job_index: 2, job_id: Basro3 }
          - { job_index: 3, job_id: Basro4 }
          - { job_index: 4, job_id: Basro5 }
          - { job_index: 5, job_id: Basro6 }
          - { job_index: 6, job_id: Basro7 }
          - { job_index: 7, job_id: Basro8 }
          - { job_index: 8, job_id: Basro9 }
          - { job_index: 9, job_id: Basro10 }
          - { job_index: 10, job_id: Basro11 }
          - { job_index: 11, job_id: Basro12 }
          - { job_index: 12, job_id: Basro13 }
          - { job_index: 13, job_id: Basro14 }
          - { job_index: 14, job_id: Basro15 }
          - { job_index: 15, job_id: Basro16 }
          - { job_index: 16, job_id: Basro17 }
          - { job_index: 17, job_id: Basro18 }
          - { job_index: 18, job_id: Basro19 }
          - { job_index: 19, job_id: Basro20 }
          - { job_index: 20, job_id: Basro21 }
          - { job_index: 21, job_id: Basro22 }
          - { job_index: 22, job_id: Basro23 }
          - { job_index: 23, job_id: Basro24 }
          - { job_index: 24, job_id: Basro25 }
          - { job_index: 25, job_id: Basro26 }
          - { job_index: 26, job_id: Basro27 }
          - { job_index: 27, job_id: Basro28 }
          - { job_index: 28, job_id: Basro29 }
          - { job_index: 29, job_id: Basro30 }
          - { job_index: 30, job_id: Basro31 }
          - { job_index: 31, job_id: Basro32 }
          - { job_index: 32, job_id: Basro33 }
          - { job_index: 33, job_id: Basro34 }
          - { job_index: 34, job_id: Basro35 }
          - { job_index: 35, job_id: Basro36 }
          - { job_index: 36, job_id: Basro37 }
          - { job_index: 37, job_id: Basro38 }
          - { job_index: 38, job_id: Basro39 }
          - { job_index: 39, job_id: Basro40 }
          - { job_index: 40, job_id: Basro41 }
          - { job_index: 41, job_id: Basro42 }
          - { job_index: 42, job_id: Basro43 }
          - { job_index: 43, job_id: Basro44 }
          - { job_index: 44, job_id: Basro45 }
          - { job_index: 45, job_id: Basro46 }
          - { job_index: 46, job_id: Basro47 }
          - { job_index: 47, job_id: Basro48 }
          - { job_index: 48, job_id: Basro49 }
          - { job_index: 49, job_id: Basro50 }
          - { job_index: 50, job_id: Basro51 }
          - { job_index: 51, job_id: Basro52 }
          - { job_index: 52, job_id: Basro53 }
          - { job_index: 53, job_id: Basro54 }
          - { job_index: 54, job_id: Basro55 }
          - { job_index: 55, job_id: Basro56 }
          - { job_index: 56, job_id: Basro57 }
          - { job_index: 57, job_id: Basro58 }
          - { job_index: 58, job_id: Basro59 }
          - { job_index: 59, job_id: Basro60 }
          - { job_index: 60, job_id: Basro61 }
          - { job_index: 61, job_id: Basro62 }
          - { job_index: 62, job_id: Basro63 }
          - { job_index: 63, job_id: Basro64 }
          - { job_index: 64, job_id: Basro65 }
          - { job_index: 65, job_id: Basro66 }
          - { job_index: 66, job_id: Basro67 }
          - { job_index: 67, job_id: Basro68 }
          - { job_index: 68, job_id: Basro69 }
          - { job_index: 69, job_id: Basro70 }
          - { job_index: 70, job_id: Basro71 }
          - { job_index: 71, job_id: Basro72 }
          - { job_index: 72, job_id: Basro73 }
          - { job_index: 73, job_id: Basro74 }
          - { job_index: 74, job_id: Basro75 }
          - { job_index: 75, job_id: Basro76 }
          - { job_index: 76, job_id: Basro77 }
          - { job_index: 77, job_id: Basro78 }
          - { job_index: 78, job_id: Basro79 }
          - { job_index: 79, job_id: Basro80 }
          - { job_index: 80, job_id: Basro81 }
          - { job_index: 81, job_id: Basro82 }
          - { job_index: 82, job_id: Basro83 }
          - { job_index: 83, job_id: Basro84 }
          - { job_index: 84, job_id: Basro85 }
          - { job_index: 85, job_id: Basro86 }
          - { job_index: 86, job_id: Basro87 }
          - { job_index: 87, job_id: Basro88 }
          - { job_index: 88, job_id: Basro89 }
          - { job_index: 89, job_id: Basro90 }
          - { job_index: 90, job_id: Basro91 }
          - { job_index: 91, job_id: Basro92 }
          - { job_index: 92, job_id: Basro93 }
          - { job_index: 93, job_id: Basro94 }
          - { job_index: 94, job_id: Basro95 }
          - { job_index: 95, job_id: Basro96 }
          - { job_index: 96, job_id: Basro97 }
          - { job_index: 97, job_id: Basro98 }
          - { job_index: 98, job_id: Basro99 }
          - { job_index: 99, job_id: Basro100 }
          - { job_index: 100, job_id: Basro101 }
          - { job_index: 101, job_id: Basro102 }
          - { job_index: 102, job_id: Basro103 }
          - { job_index: 103, job_id: Basro104 }
          - { job_index: 104, job_id: Basro105 }
          - { job_index: 105, job_id: Basro106 }
          - { job_index: 106, job_id: Basro107 }
          - { job_index: 107, job_id: Basro108 }
          - { job_index: 108, job_id: Basro109 }
          - { job_index: 109, job_id: Basro110 }
          - { job_index: 110, job_id: Basro111 }
          - { job_index: 111, job_id: Basro112 }
          - { job_index: 112, job_id: Basro113 }
          - { job_index: 113, job_id: Basro114 }
          - { job_index: 114, job_id: Basro115 }
          - { job_index: 115, job_id: Basro116 }
          - { job_index: 116, job_id: Basro117 }
          - { job_index: 117, job_id: Basro118 }
          - { job_index: 118, job_id: Basro119 }
          - { job_index: 119, job_id: Basro120 }
          - { job_index: 120, job_id: Basro121 }
          - { job_index: 121, job_id: Basro122 }
          - { job_index: 122, job_id: Basro123 }
          - { job_index: 123, job_id: Basro124 }
          - { job_index: 124, job_id: Basro125 }
          - { job_index: 125, job_id: Basro126 }
          - { job_index: 126, job_id: Basro127 }
          - { job_index: 127, job_id: Basro128 }
          - { job_index: 128, job_id: Basro129 }
          - { job_index: 129, job_id: Basro130 }
          - { job_index: 130, job_id: Basro131 }
          - { job_index: 131, job_id: Basro132 }
          - { job_index: 132, job_id: Basro133 }
          - { job_index: 133, job_id: Basro134 }
          - { job_index: 134, job_id: Basro135 }
          - { job_index: 135, job_id: Basro136 }
          - { job_index: 136, job_id: Basro137 }
          - { job_index: 137, job_id: Basro138 }
          - { job_index: 138, job_id: Basro139 }
          - { job_index: 139, job_id: Basro140 }
          - { job_index: 140, job_id: Basro141 }
          - { job_index: 141, job_id: Basro142 }
          - { job_index: 142, job_id: Basro143 }
          - { job_index: 143, job_id: Basro144 }
          - { job_index: 144, job_id: Basro145 }
          - { job_index: 145, job_id: Basro146 }
          - { job_index: 146, job_id: Basro147 }
          - { job_index: 147, job_id: Basro148 }
          - { job_index: 148, job_id: Basro149 }
          - { job_index: 149, job_id: Basro150 }
          - { job_index: 150, job_id: Basro151 }
          - { job_index: 151, job_id: Basro152 }
          - { job_index: 152, job_id: Basro153 }
          - { job_index: 153, job_id: Basro154 }
          - { job_index: 154, job_id: Basro155 }
          - { job_index: 155, job_id: Basro156 }
          - { job_index: 156, job_id: Basro157 }
          - { job_index: 157, job_id: Basro158 }
          - { job_index: 158, job_id: Basro159 }
          - { job_index: 159, job_id: Basro160 }
          - { job_index: 160, job_id: Basro161 }
          - { job_index: 161, job_id: Basro162 }
          - { job_index: 162, job_id: Basro163 }
          - { job_index: 163, job_id: Basro164 }
          - { job_index: 164, job_id: Basro165 }
          - { job_index: 165, job_id: Basro166 }
          - { job_index: 166, job_id: Basro167 }
          - { job_index: 167, job_id: Basro168 }
          - { job_index: 168, job_id: Basro169 }
          - { job_index: 169, job_id: Basro170 }
          - { job_index: 170, job_id: Basro171 }
          - { job_index: 171, job_id: Basro172 }
          - { job_index: 172, job_id: Basro173 }
          - { job_index: 173, job_id: Basro174 }
          - { job_index: 174, job_id: Basro175 }
          - { job_index: 175, job_id: Basro176 }
          - { job_index: 176, job_id: Basro177 }
          - { job_index: 177, job_id: Basro178 }
          - { job_index: 178, job_id: Basro179 }
          - { job_index: 179, job_id: Basro180 }
          - { job_index: 180, job_id: Basro181 }
          - { job_index: 181, job_id: Basro182 }
          - { job_index: 182, job_id: Basro183 }
          - { job_index: 183, job_id: Basro184 }
          - { job_index: 184, job_id: Basro185 }
          - { job_index: 185, job_id: Basro186 }
          - { job_index: 186, job_id: Basro187 }
          - { job_index: 187, job_id: Basro188 }
          - { job_index: 188, job_id: Basro189 }
          - { job_index: 189, job_id: Basro190 }
          - { job_index: 190, job_id: Basro191 }
          - { job_index: 191, job_id: Basro192 }
          - { job_index: 192, job_id: Basro193 }
          - { job_index: 193, job_id: Basro194 }
          - { job_index: 194, job_id: Basro195 }
          - { job_index: 195, job_id: Basro196 }
          - { job_index: 196, job_id: Basro197 }
          - { job_index: 197, job_id: Basro198 }
          - { job_index: 198, job_id: Basro199 }
          - { job_index: 199, job_id: Basro200 }
    env:
      HAXBALL_ROOMS: ${{ github.event.inputs.haxball_rooms }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}
      HAXBALL_PASSWORD: ${{ github.event.inputs.password }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_INDEX: ${{ matrix.job_index }}
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
